-- ConTurk production tracking database
-- Run once in the Supabase SQL editor.
-- The application uses the server-only SUPABASE_SECRET_KEY, so public clients
-- do not receive direct access to this table.

create table if not exists public.tracking_records (
  id integer generated by default as identity primary key,
  tracking_no text not null,
  current_status text not null default 'Processing',
  booking_mode text not null default 'Paid',
  scheduled_delivery text not null default '',
  customer_first_name text not null default '',
  customer_last_name text not null default '',
  origin text not null default '',
  destination text not null default '',
  services text not null default '',
  type text not null default '',
  weight text not null default '',
  pickup_date_time text not null default '',
  description text not null default '',
  shipper jsonb not null default '{"name":"","phone":"","address":""}'::jsonb,
  consignee jsonb not null default '{"name":"","phone":"","address":""}'::jsonb,
  travel_history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tracking_records_tracking_no_lower_idx
  on public.tracking_records (lower(tracking_no));

alter table public.tracking_records enable row level security;

-- No anonymous/authenticated client policies are created intentionally.
-- The Next.js server talks to Supabase with SUPABASE_SECRET_KEY.
